ARG REDIS_VER=6.2

FROM redis:${REDIS_VER}
WORKDIR /data

RUN mkdir -p /usr/lib/redis/modules
COPY /build-1.6.15/redisearch.so /usr/lib/redis/modules

EXPOSE 6379
CMD ["redis-server", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]